apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wikijs
  labels:
    app: wikijs
spec:
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
       - name: "wikijs"
         image: requarks/wiki:2.5   # OR requarks/wiki:latest
         imagePullPolicy: "IfNotPresent"
         ports:
          - containerPort: 3000
            name: http
         resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
         env:
            - name: HA_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: HA_ACTIVE
                  name: postgres-config
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  key: DB_TYPE
                  name: postgres-config
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: postgres-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: postgres-config
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                 name: postgres-secret
                 key: DATABASE_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                 name: postgres-secret
                 key: DATABASE_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                 name: postgres-secret
                 key: DATABASE_PASSWORD
      