apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wikijs
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  type: LoadBalancer
  selector:
    app: wikijs
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP