apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: wikijs
type: Opaque
data:
  DATABASE_NAME: d2lraWpzZGI= # is used to create a database to be used as the default.
  DATABASE_USER: d2lraWpz # is used to create a superuser with the name set in the environment variable.
  DATABASE_PASSWORD: V2lraWpzVXNlclBhc3N3MHJk # is used to set the superuser password