apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: wikijs
  labels:
    app: postgres # Labels and Selectors
    service: postgres
spec:
  #type: NodePort # Sets service type
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432 